emptyCohortTable overwrite argument
darwin-eu-dev/omopgenerics pull request #321
Opened 2024-05-12 18:25 UTC by nmercadeb

2024-05-12 19:33 UTC, catalamarti requested changes

2024-05-12 19:33 UTC, catalamarti commented on R/classCohortTable.R
> +emptyCohortTable <- function(cdm, name, overwrite = FALSE) {
in line with the rest of the functions can we set: overwrite = TRUE? @nmercadeb

2024-05-12 21:45 UTC, nmercadeb commented on R/classCohortTable.R
> +emptyCohortTable <- function(cdm, name, overwrite = FALSE) {
I put FALSE to preserve the current functionality, but happy to change it!

2024-05-13 09:13 UTC, catalamarti approved these changes

2024-05-13 09:13 UTC, merged