cohort error if not permanent tbl
darwin-eu-dev/omopgenerics pull request #421
Opened 2024-07-29 08:14 UTC by edward-burn

closes #413

2024-07-29 08:54 UTC, catalamarti requested changes
can we write the code in a function and call it twice?

2024-07-29 10:01 UTC, catalamarti commented
Should they keep the class if they are temporal tables?

I would write a method for `compute.cohort_table`:
- If it is permanent table -> the attributes are copied to the `new_table_name_set`
- if temporary, we lose the attributes.

What do you think? @edward-burn 
I can open a separate issue to discuss that

2024-07-29 10:02 UTC, edward-burn commented
> Should they keep the class if they are temporal tables?
> 
> I would write a method for `compute.cohort_table`:
> 
>     * If it is permanent table -> the attributes are copied to the `new_table_name_set`
> 
>     * if temporary, we lose the attributes.
> 
> 
> What do you think? @edward-burn I can open a separate issue to discuss that

@catalamarti yes let's make it a separate issue

2024-08-01 08:39 UTC, catalamarti approved these changes

2024-08-01 10:40 UTC, merged