validate  Window
darwin-eu-dev/omopgenerics pull request #422
Opened 2024-07-30 07:56 UTC by ilovemane

2024-07-30 07:58 UTC, ilovemane commented
need discussion

2024-08-05 14:05 UTC, catalamarti requested changes

2024-08-05 14:05 UTC, catalamarti commented on R/validate.R
> +  assertLogical(snakeCase, length = 1)
pass call argument

2024-08-05 14:31 UTC, ilovemane commented on R/validate.R
> +  assertLogical(snakeCase, length = 1)
added

2024-08-05 15:04 UTC, merged