age Group
darwin-eu-dev/omopgenerics pull request #424
Opened 2024-07-30 11:23 UTC by ilovemane

2024-08-02 08:48 UTC, catalamarti commented
argument to determine if `multiple` age groups are allowed or not

2024-08-05 14:08 UTC, catalamarti requested changes

2024-08-05 14:08 UTC, catalamarti commented on R/validate.R
> +  assertLogical(multipleAgeGroup, length = 1)
pass call argument

2024-08-05 14:08 UTC, catalamarti commented on R/validate.R
> +  assertLogical(overlap, length = 1)
pass call argument

2024-08-05 14:08 UTC, catalamarti commented on R/validate.R
> +                                     multipleAgeGroup = TRUE,
should default be false? to discuss @edward-burn

2024-08-05 14:08 UTC, catalamarti commented on R/validate.R
> +                                     call = parent.frame()){
add argument null = TRUE/FALSE to assess if NULL is allowed or not

2024-08-05 14:25 UTC, ilovemane commented on R/validate.R
> +                                     call = parent.frame()){
added @catalamarti

2024-08-05 14:28 UTC, catalamarti approved these changes

2024-08-05 14:55 UTC, merged