assertDate
darwin-eu-dev/omopgenerics pull request #466
Opened 2024-08-09 09:28 UTC by ilovemane

I need this in omock

2024-08-09 13:07 UTC, ilovemane commented
include                             na = FALSE,
                            null = FALSE,
                            unique = FALSE,
                            named = FALSE,

2024-08-09 14:58 UTC, ilovemane commented
this should be fine now

2024-08-14 20:55 UTC, catalamarti requested changes

2024-08-14 20:55 UTC, catalamarti commented on R/assert.R
> +                       length,
can we have default of length = NULL, so any length it is allowed by default?

2024-08-15 21:22 UTC, ilovemane commented on R/assert.R
> +                       length,
done

2024-08-16 20:30 UTC, catalamarti commented
thanks @ilovemane

2024-08-16 20:30 UTC, merged