validate person id in clinical table is in person table
darwin-eu-dev/omopgenerics pull request #497
Opened 2024-09-10 08:12 UTC by ilovemane

2024-09-10 09:18 UTC, catalamarti requested changes

2024-09-10 09:18 UTC, catalamarti commented on R/classCdmReference.R
> +    if (isTRUE(nrow(x |> utils::head(1) |> dplyr::collect()) > 0)) {
else return()

2024-09-10 09:18 UTC, catalamarti commented on R/classCdmReference.R
> +    if (!inherits(x, "tbl")) {
this if is not needed

2024-09-10 09:18 UTC, catalamarti commented on R/classCdmReference.R
> +checkPerson <- function(cdm, tableName, id, call = parent.frame) {
parent.frame()

2024-09-10 09:18 UTC, catalamarti commented on R/validate.R
> +   id <- cdm$person |> dplyr::pull(.data$person_id)
would be nice to have this inside the code

2024-09-10 09:18 UTC, catalamarti commented on R/validate.R
> +   tableName <- c("observation_period","visit_occurrence",
check all the tables, not have a prior list

2024-09-10 09:18 UTC, catalamarti commented on R/validate.R
> +   tableName <- c("observation_period","visit_occurrence",
inside you check if person_id or subject_id are columns and then you check

2024-09-10 09:18 UTC, catalamarti commented on R/validate.R
> +   tableName <- c("observation_period","visit_occurrence",
try to run in database side:
cdm$my_table |> dplyr::anti_join(cdm$perosn) |> head(1) |> dplyr::collect()

2024-09-10 13:26 UTC, ilovemane commented
@catalamarti  This should be ok now

2024-09-10 21:34 UTC, catalamarti requested changes

2024-09-10 21:34 UTC, catalamarti commented on R/classCdmReference.R
> +  # check for table with persion_id or subject_id
tableName <- names(cdm)
tableName <- tableName [purrr::map_lgl(tableName, \(x) any(c("person_id", "subject_id") %in% colnames(cdm[[x]])))]

2024-09-10 21:34 UTC, catalamarti commented on R/classCdmReference.R
> +checkPerson <- function(cdm, call = parent.frame()) {
Could we do it without leaving the database?
```
tables <- names(cdm) |>
  rang::set_names() |>
  purrr::map_lgl(\(x) {
    id <- c("person_id", "subject_id")
    id <- id[id %in% colnames(cdm[[x]])]
    if (length(id) == 1) {
      cdm[[x]] |>
        dplyr::select("person_id" = dplyr::all_of(id)) |>
        dplyr::anti_join(cdm$person, by = "person_id") |>
        utils::head(1) |>
        dplyr::tally() |>
        dplyr::pull() > 0
    } else {
      FALSE
    }
  })
Ann then report the trues? Do you think something like that would work, probably you can fins a way to make the code a bit more elegant.
```

2024-09-11 10:37 UTC, ilovemane commented on R/classCdmReference.R
> +checkPerson <- function(cdm, call = parent.frame()) {
i checked it to using purrr::map now

2024-09-11 16:30 UTC, catalamarti approved these changes

2024-09-11 16:30 UTC, catalamarti commented
thank you very much @ilovemane this is good to go

2024-09-11 16:46 UTC, merged