getFieldTables
darwin-eu-dev/omopgenerics pull request #500
Opened 2024-09-11 11:22 UTC by ilovemane

2024-09-11 19:19 UTC, catalamarti requested changes
Hi @ilovemane I would export it as dataset, I can show you tomorrow how to do it

2024-09-16 08:49 UTC, catalamarti commented on R/fieldsTable.R
> +"fieldsTable"
to discuss name in today's meeting

2024-09-16 09:39 UTC, catalamarti requested changes

2024-09-16 09:54 UTC, ilovemane commented
change it to a function.

2024-09-16 22:28 UTC, merged