Function combineStrata
darwin-eu-dev/omopgenerics pull request #516
Opened 2024-09-18 15:25 UTC by KimLopezGuell

Close #505

2024-09-18 16:25 UTC, catalamarti requested changes
@KimLopezGuell thank you very much, very minor things

2024-09-18 16:25 UTC, catalamarti commented on R/combineStrata.R
> +  result <- lapply(c(1:length(levels)), combn, x = levels, simplify = FALSE) |>
I like more purrr: although it is the same hahahaha
purrr::map(seq_along(levels), \(x) combn(x = levels, m = x, simplify = FALSE))

2024-09-18 16:25 UTC, catalamarti commented on R/combineStrata.R
> +  if(length(levels) < 2) {cli::cli_abort("strata vector must have at least two levels.")}
If the input levels is character (or NULL) I would not throw error:
just return(list()) if length(levels) == 0 and let purrr::map handle the rest (for length 1 arguments it works fine

2024-09-18 18:59 UTC, catalamarti commented
hi @KimLopezGuell I've made NA to work, I don't think it is omopgenerics to judge if NA is a correct strata value or not. What do you think?

2024-09-18 18:59 UTC, catalamarti approved these changes

2024-09-19 08:04 UTC, KimLopezGuell commented
That works for me. Thank you @catalamarti

2024-09-19 09:48 UTC, merged